<a href="https://colab.research.google.com/github/garrick-watkins/MIS-433/blob/main/Copy_of_assignment_data_manipuation_flights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation in Pandas

In this assignment, you will be working on the same dataframe of flights departing New York City in 2013.

In [1]:
import pandas as pd

In [4]:
# Install the package 'nycflights13' before you can run this
!pip install nycflights13
from nycflights13 import flights
flights.head()

Collecting nycflights13
  Downloading nycflights13-0.0.3.tar.gz (8.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 51.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from nycflights13) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->nycflights13) (1.17.0)
Building wheels for collected packages: nycflights13
  Building wheel for nycflights13 (setup.py) ... done
  Created wheel for nycflights13: filename=nycflights13-0.0.3-py3-none-any.whl size=8732722 sha256=83f9bfa6a5d9abb1c6a65f93305df72d20dd7f085e094629721c5f495538e211
  Stored in directory: /root/.cache/pip/wheels/58/ee/20/7838832df5510701439239ec10c2d8927de32aac2729ce2085
Successfully built nycflights13
Installing collected packages: nycflights13
Successfully installed nycflights13-0.0.3

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

In [ ]:
flights.shape

## Data frame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [5]:
# use describe() to summarize all columns
flights.describe(include='all')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
count,336776.0,336776.000000,336776.000000,328521.000000,336776.000000,328521.000000,328063.000000,336776.000000,327346.000000,336776,336776.000000,334264,336776,336776,327346.000000,336776.000000,336776.000000,336776.000000,336776
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,4043,3,105,NaN,NaN,NaN,NaN,6936
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA,NaN,N725MQ,EWR,ORD,NaN,NaN,NaN,NaN,2013-09-13T12:00:00Z
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58665,NaN,575,120835,17283,NaN,NaN,NaN,NaN,94
mean,2013.0,6.548510,15.710787,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,NaN,1971.923620,NaN,NaN,NaN,150.686460,1039.912604,13.180247,26.230100,NaN
std,0.0,3.414457,8.768607,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,NaN,1632.471938,NaN,NaN,NaN,93.688305,733.233033,4.661316,19.300846,NaN
min,2013.0,1.000000,1.000000,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,NaN,1.000000,NaN,NaN,NaN,20.000000,17.000000,1.000000,0.000000,NaN
25%,2013.0,4.000000,8.000000,907.000000,906.000000,-5.000000,1104.000000,1124.000000,-17.000000,NaN,553.000000,NaN,NaN,NaN,82.000000,502.000000,9.000000,8.000000,NaN
50%,2013.0,7.000000,16.000000,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,NaN,1496.000000,NaN,NaN,NaN,129.000000,872.000000,13.000000,29.000000,NaN
75%,2013.0,10.000000,23.000000,1744.000000,1729.000000,11.000000,1940.000000,1945.000000,14.000000,NaN,3465.000000,NaN,NaN,NaN,192.000000,1389.000000,17.000000,44.000000,NaN
max,2013.0,12.000000,31.000000,2400.000000,2359.000000,1301.000000,2400.000000,2359.000000,1272.000000,NaN,8500.000000,NaN,NaN,NaN,695.000000,4983.000000,23.000000,59.000000,NaN

## Question 1. Selecting rows

From the 'flights' dataframe, find all flights that satisfy the following certain conditions:

In [37]:
# Had an arrival delay of two or more hours
print(flights[flights['arr_delay'] >= 120])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
119     2013      1    1     811.0             630      101.0    1047.0
151     2013      1    1     848.0            1835      853.0    1001.0
218     2013      1    1     957.0             733      144.0    1056.0
268     2013      1    1    1114.0             900      134.0    1447.0
447     2013      1    1    1505.0            1310      115.0    1638.0
...      ...    ...  ...       ...             ...        ...       ...
336579  2013      9   30    1823.0            1545      158.0    1934.0
336668  2013      9   30    1951.0            1649      182.0    2157.0
336724  2013      9   30    2053.0            1815      158.0    2310.0
336757  2013      9   30    2159.0            1845      194.0    2344.0
336763  2013      9   30    2235.0            2001      154.0      59.0

        sched_arr_time  arr_delay carrier  ...  dest air_time distance hour  \
119                830      137.0      MQ  ...   CLT    118.0      544    6
151               1950      851.0      MQ  ...   BWI     41.0      184   18
218                853      123.0      UA  ...   BOS     37.0      200    7
268               1222      145.0      UA  ...   IAH    248.0     1416    9
447               1431      127.0      EV  ...   RIC     63.0      277   13
...                ...        ...     ...  ...   ...      ...      ...  ...
336579            1733      121.0      9E  ...   BNA     95.0      765   15
336668            1903      174.0      EV  ...   SAV     95.0      708   16
336724            2054      136.0      EV  ...   ATL     91.0      746   18
336757            2030      194.0      9E  ...   BUF     50.0      301   18
336763            2249      130.0      B6  ...   MCO    123.0      944   20

        minute             time_hour  dep_time_min  arr_to_dep  \
119         30  2013-01-01T11:00:00Z         491.0       236.0
151         35  2013-01-01T23:00:00Z         528.0       153.0
218         33  2013-01-01T12:00:00Z         597.0        99.0
268          0  2013-01-01T14:00:00Z         674.0       333.0
447         10  2013-01-01T18:00:00Z         905.0       133.0
...        ...                   ...           ...         ...
336579      45  2013-09-30T19:00:00Z        1103.0       111.0
336668      49  2013-09-30T20:00:00Z        1191.0       206.0
336724      15  2013-09-30T22:00:00Z        1253.0       257.0
336757      45  2013-09-30T22:00:00Z        1319.0       185.0
336763       1  2013-10-01T00:00:00Z        1355.0     -2176.0

       dep_delay_verifier       speed
119                 181.0  276.610169
151                -987.0  269.268293
218                 224.0  324.324324
268                 214.0  342.580645
447                 195.0  263.809524
...                   ...         ...
336579              278.0  483.157895
336668              302.0  447.157895
336724              238.0  491.868132
336757              314.0  361.200000
336763              234.0  460.487805

[10200 rows x 23 columns]

In [36]:
# Flew to Houston (IAH or HOU)
print(flights[(flights['dest'] == 'IAH') | (flights['dest'] == 'HOU')])

(9313, 23)

In [11]:
# Were operated by United (UA), American (AA), or Delta (DL)
print(flights[(flights['carrier'] == 'UA') | (flights['carrier'] == 'AA') |(flights['carrier'] == 'DL')])

(139504, 19)

In [12]:
# Departed in July, August, and September
print(flights[(flights['month'] == 7) | (flights['month'] == 8) | (flights['month'] == 9)])

(86326, 19)

In [13]:
# Arrived more than two hours late, but didn’t leave late
print(flights[(flights['arr_delay'] > 120) & (flights['dep_delay'] <= 0)])

(29, 19)

In [14]:
# Were delayed by at least an hour, but made up over 30 minutes in flight
print(flights[(flights['dep_delay'] >= 60) & (flights['arr_delay'] - flights['dep_delay'] > 30)])

(1948, 19)

In [ ]:
# Departed between midnight and 6am (inclusive)
print(flights[(flights['dep_time'] >= 0) & (flights['dep_time'] <= 600)])

In [15]:
# How many flights have a missing dep_time?
print(flights[flights['dep_time'].isnull()])

(8255, 19)

## Question 2. Sorting

In [40]:
# Sort flights to find the least delayed flights. Find the flights that left earliest.
print(flights.sort_values(by=['dep_delay', 'dep_time']).head())

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
89673   2013     12    7    2040.0            2123      -43.0      40.0
113633  2013      2    3    2022.0            2055      -33.0    2240.0
64501   2013     11   10    1408.0            1440      -32.0    1549.0
9619    2013      1   11    1900.0            1930      -30.0    2233.0
24915   2013      1   29    1703.0            1730      -27.0    1947.0

        sched_arr_time  arr_delay carrier  ...  dest air_time distance hour  \
89673             2352       48.0      B6  ...   DEN    265.0     1626   21
113633            2338      -58.0      DL  ...   MSY    162.0     1183   20
64501             1559      -10.0      EV  ...   IAD     52.0      229   14
9619              2243      -10.0      DL  ...   TPA    139.0     1010   19
24915             1957      -10.0      F9  ...   DEN    250.0     1620   17

        minute             time_hour  dep_time_min  arr_to_dep  \
89673       23  2013-12-08T02:00:00Z        1240.0     -2000.0
113633      55  2013-02-04T01:00:00Z        1222.0       218.0
64501       40  2013-11-10T19:00:00Z         848.0       141.0
9619        30  2013-01-12T00:00:00Z        1140.0       333.0
24915       30  2013-01-29T22:00:00Z        1023.0       244.0

       dep_delay_verifier       speed
89673               -83.0  368.150943
113633              -33.0  438.148148
64501               -32.0  264.230769
9619                -30.0  435.971223
24915               -27.0  388.800000

[5 rows x 23 columns]

In [17]:
# Which flights travelled the farthest? Which travelled the shortest?
print(flights.sort_values(by='distance', ascending=False).head())
print(flights.sort_values(by='distance').head())

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
118311  2013      2    9    1206.0             900      186.0    1814.0
227103  2013      6    6    1044.0            1000       44.0    1441.0
224146  2013      6    3     957.0            1000       -3.0    1432.0
170226  2013      4    6     957.0            1000       -3.0    1510.0
130088  2013      2   22     857.0             900       -3.0    1436.0

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
118311            1540      154.0      HA      51  N380HA    JFK  HNL
227103            1435        6.0      HA      51  N384HA    JFK  HNL
224146            1435       -3.0      HA      51  N381HA    JFK  HNL
170226            1510        0.0      HA      51  N382HA    JFK  HNL
130088            1540      -64.0      HA      51  N382HA    JFK  HNL

        air_time  distance  hour  minute             time_hour
118311     645.0      4983     9       0  2013-02-09T14:00:00Z
227103     580.0      4983    10       0  2013-06-06T14:00:00Z
224146     605.0      4983    10       0  2013-06-03T14:00:00Z
170226     638.0      4983    10       0  2013-04-06T14:00:00Z
130088     606.0      4983     9       0  2013-02-22T14:00:00Z
        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
275945  2013      7   27       NaN             106        NaN       NaN
116412  2013      2    6    2125.0            2129       -4.0    2207.0
164109  2013      3   30    1942.0            1950       -8.0    2026.0
150994  2013      3   16    1947.0            1950       -3.0    2055.0
19088   2013      1   22    2203.0            2130       33.0    2317.0

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
275945             245        NaN      US    1632     NaN    EWR  LGA
116412            2224      -17.0      EV    4619  N12564    EWR  PHL
164109            2044      -18.0      EV    4457  N12569    EWR  PHL
150994            2044       11.0      EV    4457  N48901    EWR  PHL
19088             2225       52.0      EV    4619  N13538    EWR  PHL

        air_time  distance  hour  minute             time_hour
275945       NaN        17     1       6  2013-07-27T05:00:00Z
116412      28.0        80    21      29  2013-02-07T02:00:00Z
164109      24.0        80    19      50  2013-03-30T23:00:00Z
150994      31.0        80    19      50  2013-03-16T23:00:00Z
19088       31.0        80    21      30  2013-01-23T02:00:00Z

## Question 3. Selecting Columns

Use at least three ways to select dep_time, dep_delay, arr_time, and arr_delay from flights.

In [19]:
# Method 1
print(flights[['dep_time', 'dep_delay', 'arr_time', 'arr_delay']])

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [20]:
# Method 2
print(flights.loc[:, ['dep_time', 'dep_delay', 'arr_time', 'arr_delay']])

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [21]:
# Method 3
print(flights.iloc[:, [3, 4, 5, 6]])

        dep_time  sched_dep_time  dep_delay  arr_time
0          517.0             515        2.0     830.0
1          533.0             529        4.0     850.0
2          542.0             540        2.0     923.0
3          544.0             545       -1.0    1004.0
4          554.0             600       -6.0     812.0
...          ...             ...        ...       ...
336771       NaN            1455        NaN       NaN
336772       NaN            2200        NaN       NaN
336773       NaN            1210        NaN       NaN
336774       NaN            1159        NaN       NaN
336775       NaN             840        NaN       NaN

[336776 rows x 4 columns]

## Question 4. Adding new columns

Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers.

For example, 759 means 7:59 and 801 means 8:01. Their difference is not 42 but 2 minutes.

In [24]:
# Convert them to a more convenient representation of number of minutes since midnight (0).
#MSM = Minutes Since Midnight
dep_msm = 60 * (flights['dep_time'] // 100) + (flights['dep_time'] % 100)
flights['dep_time_min'] = dep_msm
print(flights['dep_time'], flights['dep_time_min'])

0         517.0
1         533.0
2         542.0
3         544.0
4         554.0
          ...
336771      NaN
336772      NaN
336773      NaN
336774      NaN
336775      NaN
Name: dep_time, Length: 336776, dtype: float64 0         317.0
1         333.0
2         342.0
3         344.0
4         354.0
          ...
336771      NaN
336772      NaN
336773      NaN
336774      NaN
336775      NaN
Name: dep_time_min, Length: 336776, dtype: float64

In [25]:
# Create a new column of arr_time - dep_time.
flights['arr_to_dep'] = flights['arr_time'] - flights['dep_time']

# Compare this column with air_time.
print(flights['air_time'], flights['arr_to_dep'])

0         227.0
1         227.0
2         160.0
3         183.0
4         116.0
          ...
336771      NaN
336772      NaN
336773      NaN
336774      NaN
336775      NaN
Name: air_time, Length: 336776, dtype: float64 0         313.0
1         317.0
2         381.0
3         460.0
4         258.0
          ...
336771      NaN
336772      NaN
336773      NaN
336774      NaN
336775      NaN
Name: arr_to_dep, Length: 336776, dtype: float64

In [30]:
# Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
# Try creating a column to calculate dep_delay from dep_time and sched_dep_time (and/or other columns if necessary).
flights['dep_delay_verifier'] = (flights['dep_time']-flights['sched_dep_time'])

# Test your results.
print('Depature time accurate? =', (flights['dep_delay_verifier'] == flights['dep_delay']).all())

Depature time accurate? = False

## Question 5. Mixing things together

The following questions may require multiple operations above.

In [31]:
# Find the 20 most delayed flights.
# Display the following: year,month,day,carrier,flight,dep_delay,arr_delay,carrier
# How do you want to handle ties?
print(flights.sort_values(by='dep_delay', ascending=False).head(20))

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
7072    2013      1    9     641.0             900     1301.0    1242.0
235778  2013      6   15    1432.0            1935     1137.0    1607.0
8239    2013      1   10    1121.0            1635     1126.0    1239.0
327043  2013      9   20    1139.0            1845     1014.0    1457.0
270376  2013      7   22     845.0            1600     1005.0    1044.0
173992  2013      4   10    1100.0            1900      960.0    1342.0
151974  2013      3   17    2321.0             810      911.0     135.0
247040  2013      6   27     959.0            1900      899.0    1236.0
270987  2013      7   22    2257.0             759      898.0     121.0
87238   2013     12    5     756.0            1700      896.0    1058.0
195711  2013      5    3    1133.0            2055      878.0    1250.0
151     2013      1    1     848.0            1835      853.0    1001.0
210174  2013      5   19     713.0            1700      853.0    1007.0
119784  2013      2   10    2243.0             830      853.0     100.0
99938   2013     12   19     734.0            1725      849.0    1046.0
98014   2013     12   17     705.0            1700      845.0    1026.0
95530   2013     12   14     830.0            1845      825.0    1210.0
182478  2013      4   19     912.0            1940      812.0    1228.0
246911  2013      6   27     753.0            1830      803.0     937.0
152312  2013      3   18    1020.0            2100      800.0    1336.0

        sched_arr_time  arr_delay carrier  ...  origin dest air_time distance  \
7072              1530     1272.0      HA  ...     JFK  HNL    640.0     4983
235778            2120     1127.0      MQ  ...     JFK  CMH     74.0      483
8239              1810     1109.0      MQ  ...     EWR  ORD    111.0      719
327043            2210     1007.0      AA  ...     JFK  SFO    354.0     2586
270376            1815      989.0      MQ  ...     JFK  CVG     96.0      589
173992            2211      931.0      DL  ...     JFK  TPA    139.0     1005
151974            1020      915.0      DL  ...     LGA  MSP    167.0     1020
247040            2226      850.0      DL  ...     JFK  PDX    313.0     2454
270987            1026      895.0      DL  ...     LGA  ATL    109.0      762
87238             2020      878.0      AA  ...     EWR  MIA    149.0     1085
195711            2215      875.0      MQ  ...     EWR  ORD    112.0      719
151               1950      851.0      MQ  ...     JFK  BWI     41.0      184
210174            1955      852.0      AA  ...     JFK  LAS    323.0     2248
119784            1106      834.0      F9  ...     LGA  DEN    233.0     1620
99938             2039      847.0      DL  ...     EWR  SLC    290.0     1969
98014             2020      846.0      AA  ...     EWR  MIA    145.0     1085
95530             2154      856.0      DL  ...     JFK  TPA    173.0     1005
182478            2247      821.0      DL  ...     LGA  TPA    174.0     1010
246911            2015      802.0      AA  ...     LGA  STL    134.0      888
152312              32      784.0      DL  ...     JFK  LAX    335.0     2475

        hour  minute             time_hour  dep_time_min arr_to_dep  \
7072       9       0  2013-01-09T14:00:00Z         401.0      601.0
235778    19      35  2013-06-15T23:00:00Z         872.0      175.0
8239      16      35  2013-01-10T21:00:00Z         681.0      118.0
327043    18      45  2013-09-20T22:00:00Z         699.0      318.0
270376    16       0  2013-07-22T20:00:00Z         525.0      199.0
173992    19       0  2013-04-10T23:00:00Z         660.0      242.0
151974     8      10  2013-03-17T12:00:00Z        1401.0    -2186.0
247040    19       0  2013-06-27T23:00:00Z         599.0      277.0
270987     7      59  2013-07-22T11:00:00Z        1377.0    -2136.0
87238     17       0  2013-12-05T22:00:00Z         476.0      302.0
195711    20      55  2013-05-04T00:00:00Z         693.0      117.0
151       18      35  2013-01-01T23:00:00Z         528.0      153.0
210174    17       0  2013-05-19T21:00:00Z         433.0      294.0
119784     8      30  2013-02-10T13:00:00Z        1363.0    -2143.0
99938     17      25  2013-12-19T22:00:00Z         454.0      312.0
98014     17       0  2013-12-17T22:00:00Z         425.0      321.0
95530     18      45  2013-12-14T23:00:00Z         510.0      380.0
182478    19      40  2013-04-19T23:00:00Z         552.0      316.0
246911    18      30  2013-06-27T22:00:00Z         473.0      184.0
152312    21       0  2013-03-19T01:00:00Z         620.0      316.0

        dep_delay_verifier
7072                -259.0
235778              -503.0
8239                -514.0
327043              -706.0
270376              -755.0
173992              -800.0
151974              1511.0
247040              -941.0
270987              1498.0
87238               -944.0
195711              -922.0
151                 -987.0
210174              -987.0
119784              1413.0
99938               -991.0
98014               -995.0
95530              -1015.0
182478             -1028.0
246911             -1077.0
152312             -1080.0

[20 rows x 22 columns]

In [33]:
# Sort all AA flights to find the top 10 fastest (highest speed) flights.
# Display the following: year,month,day,carrier,flight,origin,dest,distance,air_time,speed (miles per hour)

# Calculate speed (miles per minute first, then convert to miles per hour)
flights['speed'] = flights['distance'] / (flights['air_time'] / 60)

# Filter for AA flights, sort by speed, select top 10, and then select desired columns
fastest_aa_flights = flights[flights['carrier'] == 'AA'].sort_values(by='speed', ascending=False).head(10)
print(fastest_aa_flights[['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'distance', 'air_time', 'speed']])

        year  month  day carrier  flight origin dest  distance  air_time  \
70704   2013     11   17      AA     936    JFK  STT      1623     175.0
87723   2013     12    5      AA    1029    JFK  SJU      1598     173.0
119700  2013      2   10      AA    1613    JFK  SJU      1598     173.0
129686  2013      2   21      AA    1613    JFK  SJU      1598     174.0
87575   2013     12    5      AA      95    JFK  SJU      1598     175.0
144408  2013      3    9      AA    1613    JFK  SJU      1598     176.0
70721   2013     11   17      AA    1357    JFK  SJU      1598     176.0
70335   2013     11   16      AA      95    JFK  SJU      1598     177.0
119477  2013      2   10      AA    1635    JFK  SJU      1598     177.0
119894  2013      2   11      AA     413    JFK  SJU      1598     177.0

             speed
70704   556.457143
87723   554.219653
119700  554.219653
129686  551.034483
87575   547.885714
144408  544.772727
70721   544.772727
70335   541.694915
119477  541.694915
119894  541.694915

In [39]:
# Find all flights that satisfy the following:
# - From John F. Kennedy Airpot (JFK) or Newark Aiport (EWR) to Seattle-Tacoma Airport (SEA)
# - Carrier is UA, AA, or DL.
# - Dates from 4/1/2013 (inclusive) to 4/3/2013 (inclusive)
# - Scheduled arrival time is before noon.
# - Display the following: year,month,day,carrier,flight,origin,dest,sched_dep_time,sched_arr_time
# - Sort by year, month, day, sched_arr_time
filtered_flights = flights[
    (flights['origin'] == 'JFK') | (flights['origin'] == 'EWR')
    & (flights['dest'] == 'SEA')
    & (flights['carrier'] == 'UA') | (flights['carrier'] == 'AA')
    |(flights['carrier'] == 'DL')
    & (flights['year'] == 2013) & (flights['month'] == 4) & (flights['day'] >= 1)
    & (flights['day'] <= 3)
    & (flights['sched_arr_time'] < 1200)
]

print(filtered_flights[['year','month','day','carrier','flight','origin','dest',
      'sched_dep_time','sched_arr_time']]
      .sort_values(by=['year','month','day','sched_arr_time']))

        year  month  day carrier  flight origin dest  sched_dep_time  \
827     2013      1    1      B6      30    JFK  ROC            2245
829     2013      1    1      B6     112    JFK  BUF            2255
795     2013      1    1      DL    1668    JFK  LAS            2110
832     2013      1    1      B6     199    JFK  LAS            2130
820     2013      1    1      B6      21    JFK  TPA            2130
...      ...    ...  ...     ...     ...    ...  ...             ...
111241  2013     12   31      B6     329    JFK  RSW            2046
111231  2013     12   31      AA    1029    JFK  SJU            1900
111240  2013     12   31      B6     523    JFK  LAX            2040
111253  2013     12   31      B6    1295    JFK  AUS            2045
111258  2013     12   31      B6    1677    JFK  JAX            2130

        sched_arr_time
827                  5
829                 15
795                 17
832                 18
820                 27
...                ...
111241            2358
111231            2359
111240            2359
111253            2359
111258            2359

[131403 rows x 9 columns]